chat:
  auto_reply: true
early_access: true
language: en
reviews:
  auto_review:
    enabled: true
  path_filters:
    - '!Assets/TextMesh Pro/**/*'
    - '!Assets/UdonSharp/**/*'
    - '!Assets/XR/**/*'
    - '!Packages/com.vrchat.core.*/**/*'
    - '!ProjectSettings/**/*'
  path_instructions:
    - instructions: This folder contains C# files, but these are UdonSharp and have different restrictions than standard C#. Please review with this in mind.
      path: Assets/black.kit.*/Runtime/**/*
    - instructions: Some files look broken, but they contain templates from Scriban. Please review with this in mind.
      path: Website/**/*
