name: Build Repo Listing

env:
  listPublishDirectory: Website
  pathToCi: ci

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build Release
    types:
      - completed
  release:
    types:
      - created
      - deleted
      - edited
      - published
      - released
      - unpublished

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-listing:
    name: build-listing
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Local Repository
        uses: actions/checkout@v4
      - name: Checkout Automation Repository without removing prior checkouts
        uses: actions/checkout@v4
        with:
          repository: vrchat-community/package-list-action
          path: ${{ env.pathToCi }}
          clean: false
      - name: Load cached data from previous runs
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.pathToCi }}/.nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Build Package Version Listing with Nuke
        run: ${{ env.pathToCi }}/build.cmd BuildRepoListing --root ${{ env.pathToCi }} --list-publish-directory $GITHUB_WORKSPACE/${{ env.listPublishDirectory }} --current-package-name ${{ vars.PACKAGE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare for GitHub Pages deployment
        uses: actions/configure-pages@v5
        with:
          enablement: true
          token: ${{ secrets.REPO_TOKEN }}
      - name: Upload the VPM Listing Website to GitHub Pages artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.listPublishDirectory }}
      - name: Deploy the uploaded VPM Listing Website to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Trigger the action of the curation repository
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: build-listing
          repository: kurone-kito/vpm
          token: ${{ secrets.REPO_TOKEN }}
